In [1]:
import numpy as np

In [2]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [4]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


# **nditer**



# **Fortan style ordering**

In [5]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
12
1
5
9
13
2
6
10
14
3
7
11
15


# **flags**

In [6]:
for x in np.nditer(a,flags=['external_loop'],order='F'):
    print(x)

[ 0  4  8 12]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]


In [7]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x 

In [8]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

# Iterate two broadcastable arrays concurrently

In [9]:
b=np.arange(4).reshape(4,1)
b

array([[0],
       [1],
       [2],
       [3]])

In [10]:
for x, y in np.nditer([a,b]):
    print(x,y)

0 0
1 0
4 0
9 0
16 1
25 1
36 1
49 1
64 2
81 2
100 2
121 2
144 3
169 3
196 3
225 3


In [14]:
for x in np.nditer(b ,op_flags=['readwrite']):
    x[...]=x + x 

In [12]:
b


array([[0],
       [2],
       [4],
       [6]])